vich_uploader:
    db_driver: orm

    mappings:
       aliment_image:
           uri_prefix: /image/aliments
           upload_destination: '%kernel.project_dir%/public/image/aliments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

